name = "Xiang Yun"
license = "MIT"
licenselink = "https://github.com/mdfriday/theme-xiang-yun/blob/main/LICENSE"
description = "Long Teng is a vibrant product landing page theme inspired by Chinese colors. It is designed to showcase your product or service, highlight its key features, and engage potential users. With flexible configuration options, it’s perfect for creating a visually appealing and effective online presence."

homepage = "https://github.com/mdfriday/theme-xiang-yun"
demosite = "https://xiangyun.app.mdfriday.com"

tags = ["product landing page", "hugo", "theme", "business", "marketing", "showcase", "mdfriday"]
features = ["responsive design", "customizable content", "Chinese color theme", "service showcase", "call-to-action buttons", "user trust section"]

[author]
name = "MDFriday"
homepage = "https://mdfriday.com"

min_version = "0.112.7"


