name = "Xiang Yun"
license = "MIT"
licenselink = "https://github.com/mdfriday/theme-xiang-yun/blob/main/LICENSE"
description = "**Xiang Yun**, meaning \"Auspicious Cloud,\" is a harmonious and elegant theme for showcasing MDFriday-supported themes, offering clear previews and inspiring customization options."

homepage = "https://github.com/mdfriday/theme-xiang-yun"
demosite = "https://themes.mdfriday.com"

tags = ["responsive", "gallery", "light", "showcase", "mdfriday"]
features = [
    "Modern and responsive design",
    "Customizable content with MDFriday integration",
    "Inspired by the Chinese color spectrum",
    "Showcasing MDFriday themes with clarity",
    "Built-in call-to-action buttons",
    "Highlight user trust and usage statistics",
    "Optimized for theme previews and exploration"
]

[author]
name = "MDFriday"
homepage = "https://mdfriday.com"

min_version = "0.112.7"
