baseurl         = "/"
languageCode    = "en-us"
title           = "MDFriday Themes"

[module]
[[module.imports]]
path = "github.com/mdfriday/theme-xiang-yun"

[markup.goldmark.renderer]
  unsafe = true

[blackfriday]
  plainIdAnchors = true
  config         = "config-tpl-base.toml"

[outputs]
  home = ["HTML", "RSS", "REDIR", "HEADERS"]

[mediaTypes]
  [mediaTypes."text/netlify"]
    suffixes  = [""]
    delimiter = ""

[outputFormats]
  [outputFormats.REDIR]
    mediatype      = "text/netlify"
    baseName       = "_redirects"
    isPlainText    = true
    notAlternative = true
  [outputFormats.HEADERS]
    mediatype      = "text/netlify"
    baseName       = "_headers"
    isPlainText    = true
    notAlternative = true

[related]
  threshold    = 80
  includeNewer = true
  toLower      = false

  [[related.indices]]
    name   = "tags"
    weight = 100
  [[related.indices]]
    name    = "date"
    weight  = 10
    pattern = "2006"

[social]
  twitter = "GoHugoIO"

[caches]
  [caches.images]
    dir = ":cacheDir"
    # 30 days.
    maxAge = "720h"

[imaging]
  resampleFilter = "CatmullRom"

  # Defatult JPEG quality setting. Default is 75.
  quality = 75

  anchor = "smart"

[params]
  github_repo = "https://github.com/gohugoio/hugoThemesSiteBuilder"
  gitter      = "https://gitter.im/spf13/hugo"
  forum       = "https://discourse.gohugo.io/"
  #This array is meant for disabling the Homepage button of a theme.
  noHomePage = ["hugo-theme-novela"]

  # GLOBAL = IF ANYTHING CHANGES BELOW UPDATE MAIN, DOCS, THEMES

